let timelineElements = [
    {
      id: 1,
      event: "Curriculum Development workshop organized by AICTE IDEA Lab",
      date: "16th January 2023",
      venue: "GGSIPU Main campus, Dwarka Sector 16C",
      audience: "Teachers, Staff and University Vice Chancelor of GGSIPU",
      icon: "college",
    },
    {
      id: 2,
      event: "Talk on Embedded Systems Organized by Department of Electronics at Sri Aurobindo College",
      date: "29th January 2023",
      venue: "Sri Aurobindo College, University of Delhi",
      audience: "More than 50 Students and Professors of the college",
      icon: "college",
    },
    {
      id: 3,
      event: "Embedded Design Workshop, Fabrication Demo to Students",
      date: "17 - 19th March 2023",
      venue: "NSUT, Dwarka",
      audience: "~200 Students of 4th semester ECE and 6th Semester EIOT courses",
      icon: "college",
    },
    {
      id: 4,
      event: "Practical Electronics talk at Quanta 2023 at Shivaji College",
      date: "26th March 2023",
      venue: "Shivaji College ",
      audience: "More than 200 students from Shivaji College",
      icon: "college",
    },
    {
      id: 5,
      event: "Government School Students visit around NSUT Campus",
      date: "9th April 2023",
      venue: "TI-CEPD, NSUT, Dwarka ",
      audience: "Government school students across schools from Delhi",
      icon: "school",
    },
    {
      id: 6,
      event: "School Visit to Nirmal Bharti School",
      date: "25th April 2023",
      venue: "Nirmal Bharti School, Sector 14, Dwarka ",
      audience: "Teachers, Staff and University Vice Chancelor of GGSIPU",
      icon: "school",
    },
    {
      id: 7,
      event: "School Visit to Vidya Jain Public School",
      date: "11th May 2023",
      venue: "Vidya Jain Public School, Rohini",
      audience: "400 students",
      icon: "school",
    },
    {
      id: 8,
      event: "IIITD professors visit TI-CEPD",
      date: "12th June 2023",
      venue: "TI-CEPD, NSUT, Dwarka",
      audience: "2 professors from IIITD",
      icon: "college",
    },
    {
      id: 9,
      event: "Faculty Development Programme in daulat ram college",
      date: "17th-19th July 2023",
      venue: "Daulat Aam College, Patel Marg,Maurice Nagar",
      audience: "~50 Teachers from Different college of Delhi University ",
      icon: "college",
    },
    {
      id: 10,
      event: "CDAC personnel visit TI-CEPD",
      date: "3rd August 2023",
      venue: "TI-CEPD, NSUT, Dwarka ",
      audience: "2 Officials from CDAC ,Hyderabad",
      icon: "college",
    },
    {
      id: 11,
      event: "Project demonstration to students of pranavananda school",
      date: "24th August 2023",
      venue: "Pranavananda International School. Sector - 92, Gurugram",
      audience: "~80 students of school",
      icon: "school",
    },
    {
      id: 12,
      event: "Project demonstration to Teacher of NK Bagrodiya school",
      date: "13th September 2023",
      venue: "TI-CEPD, NSUT, Dwarka",
      audience: "25 Teachers of  NK Bagrodiya school",
      icon: "school",
    },
    {
      id: 13,
      event: "PCB Fabrication workshop for students of Shaheed Rajguru College",
      date: "4th - 6th October 2023",
      venue: "Shaheed Rajguru college ,  Vasundhara Enclave",
      audience: "~100 Students of Shaheed Rajguru college",
      icon: "college",
    },
    {
      id: 14,
      event: "Project Demonstration to Students of KIET College",
      date: "11th October 2023",
      venue: "KIET college , Delhi-NCR, Ghaziabad-Meerut Road ,Ghaziabad",
      audience: "Entire 1st year batch . 1000+ students",
      icon: "college",
    },
    {
      id: 15,
      event: "Project demonstration and PCB fabrication demonstration to students and faculty of Maitreyi college",
      date: "19th October ",
      venue: "TI-CEPD, NSUT, Dwarka ",
      audience: "29 students and 9 faculty of Maitreyi college",
      icon: "college",
    },
    {
      id: 16,
      event: "KS Rangasamy College of Engineering, Tamil Nadu",
      date: "21st November 2023",
      venue: "KS Rangasamy College of Engineering, Tamil Nadu",
      audience: "50 teachers from across Tamil Nadu",
      icon: "college",
    },
    
  ];
  
  export default timelineElements;